
auth {
    fixed_users {
        enabled: false
    }
}

apiserver {
    files {
        default_storage {
            fileserver: "http://fileserver:8081"
            base_url: "http://fileserver:8081"
        }
    }
}
